In [126]:
import pandas as pd
from uuid import uuid4
import re

In [127]:
# Load CSV files into DataFrames
persons_data = pd.read_csv('persons_data.csv')
occupancy_data = pd.read_csv('occupancy_data.csv')
majors_data = pd.read_csv('majors_data.csv')
inventory_data = pd.read_csv('inventory_data.csv')

Data Cleaning

In [128]:
persons_data

,personId,firstName,lastName,email,dob,address,majors
0,7b1fb398-72d7-421e-808c-631a427bfbc4,David,Taylor,david.taylor@example.com,1992-08-15,"767 Walnut St, Georgetown, OH",Communications
1,99a4b233-2804-420b-b757-039f0f3cceb7,Jane,Wilson,jane.wilson@example.com,1969-08-20,"168 Birch St, Riverside, FL","Music, Finance"
2,cc3b2df2-a593-493e-af82-1f0d11c7439b,John,Brown,john.brown@example.com,1967-12-14,"726 Maple St, Fairview, PA",NaN
3,cb669177-4020-4284-a3dc-9a0c312411d4,Linda,Taylor,linda.taylor@example.com,1983-12-04,"171 Spruce St, Riverside, TX","Social Work, Anthropology"
4,ba1443a2-dfeb-441b-b41d-078b36416704,Sarah,Doe,sarah.doe@example.com,1986-08-31,"987 Walnut St, Georgetown, OH","Psychology, Criminal Justice, History, Foreign..."
...,...,...,...,...,...,...,...
4995,bc90a95b-9d36-4905-aa0f-636f5c1e4216,Jane,Miller,jane.miller@example.com,1991-08-07,"654 Pine St, Greenville, IL",Anthropology
4996,499eca03-0f5c-4026-859e-cd007c591ae9,Bob,Doe,bob.doe@example.com,2000-01-15,"129 Elm St, Fairview, TX","Political Science, Marketing, Criminal Justice..."
4997,b486891f-da16-452a-a27b-209a071c2f10,Sarah,Williams,sarah.williams@example.com,1975-12-20,"424 Spruce St, Madison, FL","Art, Nursing, Foreign Languages"
4998,f7672679-6fbf-43ae-8593-cb267ab35a56,John,Wilson,john.wilson@example.com,1967-04-02,"866 Birch St, Madison, OH",NaN
4999,bcd7282a-5497-43bc-88fd-5b5ec3b0e5ce,Emily,Smith,emily.smith@example.com,1960-01-01,"214 Elm St, Fairview, CA",NaN

In [129]:
# Remove duplicate emails, keep the first occurrence
persons_data = persons_data.drop_duplicates(subset='email', keep='first')

In [130]:
persons_data

,personId,firstName,lastName,email,dob,address,majors
0,7b1fb398-72d7-421e-808c-631a427bfbc4,David,Taylor,david.taylor@example.com,1992-08-15,"767 Walnut St, Georgetown, OH",Communications
1,99a4b233-2804-420b-b757-039f0f3cceb7,Jane,Wilson,jane.wilson@example.com,1969-08-20,"168 Birch St, Riverside, FL","Music, Finance"
2,cc3b2df2-a593-493e-af82-1f0d11c7439b,John,Brown,john.brown@example.com,1967-12-14,"726 Maple St, Fairview, PA",NaN
3,cb669177-4020-4284-a3dc-9a0c312411d4,Linda,Taylor,linda.taylor@example.com,1983-12-04,"171 Spruce St, Riverside, TX","Social Work, Anthropology"
4,ba1443a2-dfeb-441b-b41d-078b36416704,Sarah,Doe,sarah.doe@example.com,1986-08-31,"987 Walnut St, Georgetown, OH","Psychology, Criminal Justice, History, Foreign..."
...,...,...,...,...,...,...,...
318,2045e65b-0845-4d48-88f3-19c708a836cf,Michael,Davis,michael.davis@example.com,1991-04-24,"462 Walnut St, Madison, IL","Sociology, Economics, Computer Science"
327,c4d33385-848f-42f6-843b-220fa0b0f8fc,Michael,Williams,michael.williams@example.com,1994-08-08,"847 Walnut St, Madison, TX","Urban Planning, Architecture"
345,c4a82bb0-ba9d-446f-a121-ba7d2996c39e,Jane,Taylor,jane.taylor@example.com,1955-05-29,"766 Cedar St, Madison, FL","Sociology, Biology, Agriculture, Art"
352,0a10e180-a33a-4d04-8519-ae951f56b478,Sarah,Johnson,sarah.johnson@example.com,1999-12-18,"719 Maple St, Madison, CA","Physics, Biology, History, Social Work, Mathem..."
432,57101157-bd0a-4615-8778-df69fe8360c6,Sarah,Miller,sarah.miller@example.com,1950-06-24,"710 Elm St, Riverside, OH",Psychology

we have only 100 records after running dropping duplicates command. That means we removed all duplicate records and now we have only unique emails.

In [131]:
#separate address column into address parts
persons_data[["address1", "city", "state"]] = persons_data["address"].str.split(',', expand=True)

<ipython-input-131-db3c18fed33c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  persons_data[["address1", "city", "state"]] = persons_data["address"].str.split(',', expand=True)
<ipython-input-131-db3c18fed33c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  persons_data[["address1", "city", "state"]] = persons_data["address"].str.split(',', expand=True)
<ipython-input-131-db3c18fed33c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  persons_data[["address1", "city", "state"]] = persons_data["address"].str.split(',', expand=True)

In [132]:
persons_data

,personId,firstName,lastName,email,dob,address,majors,address1,city,state
0,7b1fb398-72d7-421e-808c-631a427bfbc4,David,Taylor,david.taylor@example.com,1992-08-15,"767 Walnut St, Georgetown, OH",Communications,767 Walnut St,Georgetown,OH
1,99a4b233-2804-420b-b757-039f0f3cceb7,Jane,Wilson,jane.wilson@example.com,1969-08-20,"168 Birch St, Riverside, FL","Music, Finance",168 Birch St,Riverside,FL
2,cc3b2df2-a593-493e-af82-1f0d11c7439b,John,Brown,john.brown@example.com,1967-12-14,"726 Maple St, Fairview, PA",NaN,726 Maple St,Fairview,PA
3,cb669177-4020-4284-a3dc-9a0c312411d4,Linda,Taylor,linda.taylor@example.com,1983-12-04,"171 Spruce St, Riverside, TX","Social Work, Anthropology",171 Spruce St,Riverside,TX
4,ba1443a2-dfeb-441b-b41d-078b36416704,Sarah,Doe,sarah.doe@example.com,1986-08-31,"987 Walnut St, Georgetown, OH","Psychology, Criminal Justice, History, Foreign...",987 Walnut St,Georgetown,OH
...,...,...,...,...,...,...,...,...,...,...
318,2045e65b-0845-4d48-88f3-19c708a836cf,Michael,Davis,michael.davis@example.com,1991-04-24,"462 Walnut St, Madison, IL","Sociology, Economics, Computer Science",462 Walnut St,Madison,IL
327,c4d33385-848f-42f6-843b-220fa0b0f8fc,Michael,Williams,michael.williams@example.com,1994-08-08,"847 Walnut St, Madison, TX","Urban Planning, Architecture",847 Walnut St,Madison,TX
345,c4a82bb0-ba9d-446f-a121-ba7d2996c39e,Jane,Taylor,jane.taylor@example.com,1955-05-29,"766 Cedar St, Madison, FL","Sociology, Biology, Agriculture, Art",766 Cedar St,Madison,FL
352,0a10e180-a33a-4d04-8519-ae951f56b478,Sarah,Johnson,sarah.johnson@example.com,1999-12-18,"719 Maple St, Madison, CA","Physics, Biology, History, Social Work, Mathem...",719 Maple St,Madison,CA
432,57101157-bd0a-4615-8778-df69fe8360c6,Sarah,Miller,sarah.miller@example.com,1950-06-24,"710 Elm St, Riverside, OH",Psychology,710 Elm St,Riverside,OH

In [133]:
# Create full name
persons_data['name'] = persons_data['firstName'] + ' ' + person_data['lastName']

<ipython-input-133-39bcdf4ad741>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  persons_data['name'] = persons_data['firstName'] + ' ' + person_data['lastName']

In [134]:
persons_data

,personId,firstName,lastName,email,dob,address,majors,address1,city,state,name
0,7b1fb398-72d7-421e-808c-631a427bfbc4,David,Taylor,david.taylor@example.com,1992-08-15,"767 Walnut St, Georgetown, OH",Communications,767 Walnut St,Georgetown,OH,David Taylor
1,99a4b233-2804-420b-b757-039f0f3cceb7,Jane,Wilson,jane.wilson@example.com,1969-08-20,"168 Birch St, Riverside, FL","Music, Finance",168 Birch St,Riverside,FL,Jane Wilson
2,cc3b2df2-a593-493e-af82-1f0d11c7439b,John,Brown,john.brown@example.com,1967-12-14,"726 Maple St, Fairview, PA",NaN,726 Maple St,Fairview,PA,John Brown
3,cb669177-4020-4284-a3dc-9a0c312411d4,Linda,Taylor,linda.taylor@example.com,1983-12-04,"171 Spruce St, Riverside, TX","Social Work, Anthropology",171 Spruce St,Riverside,TX,Linda Taylor
4,ba1443a2-dfeb-441b-b41d-078b36416704,Sarah,Doe,sarah.doe@example.com,1986-08-31,"987 Walnut St, Georgetown, OH","Psychology, Criminal Justice, History, Foreign...",987 Walnut St,Georgetown,OH,Sarah Doe
...,...,...,...,...,...,...,...,...,...,...,...
318,2045e65b-0845-4d48-88f3-19c708a836cf,Michael,Davis,michael.davis@example.com,1991-04-24,"462 Walnut St, Madison, IL","Sociology, Economics, Computer Science",462 Walnut St,Madison,IL,Michael Davis
327,c4d33385-848f-42f6-843b-220fa0b0f8fc,Michael,Williams,michael.williams@example.com,1994-08-08,"847 Walnut St, Madison, TX","Urban Planning, Architecture",847 Walnut St,Madison,TX,Michael Williams
345,c4a82bb0-ba9d-446f-a121-ba7d2996c39e,Jane,Taylor,jane.taylor@example.com,1955-05-29,"766 Cedar St, Madison, FL","Sociology, Biology, Agriculture, Art",766 Cedar St,Madison,FL,Jane Taylor
352,0a10e180-a33a-4d04-8519-ae951f56b478,Sarah,Johnson,sarah.johnson@example.com,1999-12-18,"719 Maple St, Madison, CA","Physics, Biology, History, Social Work, Mathem...",719 Maple St,Madison,CA,Sarah Johnson
432,57101157-bd0a-4615-8778-df69fe8360c6,Sarah,Miller,sarah.miller@example.com,1950-06-24,"710 Elm St, Riverside, OH",Psychology,710 Elm St,Riverside,OH,Sarah Miller

In [135]:
# Function to map majors to their IDs
def map_majors_to_ids(majors, majors_data):
    if pd.isnull(majors):
        return ''
    major_list = [major.strip() for major in majors.split(',')]
    major_ids = majors_data[majors_data['name'].isin(major_list)]['id'].tolist()
    return ','.join(map(str, major_ids))

# Map major names to their IDs
persons_data['majorIds'] = persons_data['majors'].apply(lambda x: map_majors_to_ids(x, majors_data))

<ipython-input-135-3d801f7a997e>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  persons_data['majorIds'] = persons_data['majors'].apply(lambda x: map_majors_to_ids(x, majors_data))

The map_majors_to_ids function splits the comma-separated majors, matches them with majors_data[name], and collects the corresponding id values.
These id values are then joined into a comma-separated string and assigned to the majorIds column.

In [136]:
persons_data

,personId,firstName,lastName,email,dob,address,majors,address1,city,state,name,majorIds
0,7b1fb398-72d7-421e-808c-631a427bfbc4,David,Taylor,david.taylor@example.com,1992-08-15,"767 Walnut St, Georgetown, OH",Communications,767 Walnut St,Georgetown,OH,David Taylor,"2c6e4248-da4d-4cb3-ac58-3cd04aa203fa,c8e9582b-..."
1,99a4b233-2804-420b-b757-039f0f3cceb7,Jane,Wilson,jane.wilson@example.com,1969-08-20,"168 Birch St, Riverside, FL","Music, Finance",168 Birch St,Riverside,FL,Jane Wilson,"49f57722-52fb-47b6-8e1e-54de177e0d19,e00c66ff-..."
2,cc3b2df2-a593-493e-af82-1f0d11c7439b,John,Brown,john.brown@example.com,1967-12-14,"726 Maple St, Fairview, PA",NaN,726 Maple St,Fairview,PA,John Brown,
3,cb669177-4020-4284-a3dc-9a0c312411d4,Linda,Taylor,linda.taylor@example.com,1983-12-04,"171 Spruce St, Riverside, TX","Social Work, Anthropology",171 Spruce St,Riverside,TX,Linda Taylor,"37b765f0-fc71-4c9c-838b-f3a5ce0706ff,8402b4cd-..."
4,ba1443a2-dfeb-441b-b41d-078b36416704,Sarah,Doe,sarah.doe@example.com,1986-08-31,"987 Walnut St, Georgetown, OH","Psychology, Criminal Justice, History, Foreign...",987 Walnut St,Georgetown,OH,Sarah Doe,"4d0b9e50-43d1-4da0-af2b-97d510bab9e2,f6cf2da9-..."
...,...,...,...,...,...,...,...,...,...,...,...,...
318,2045e65b-0845-4d48-88f3-19c708a836cf,Michael,Davis,michael.davis@example.com,1991-04-24,"462 Walnut St, Madison, IL","Sociology, Economics, Computer Science",462 Walnut St,Madison,IL,Michael Davis,"12c5d420-9bbc-455d-9794-7780bc5fea5b,2c4e188e-..."
327,c4d33385-848f-42f6-843b-220fa0b0f8fc,Michael,Williams,michael.williams@example.com,1994-08-08,"847 Walnut St, Madison, TX","Urban Planning, Architecture",847 Walnut St,Madison,TX,Michael Williams,"e0bad25d-7fb1-4dd7-a0e8-a11b41dcd281,fa7f1f45-..."
345,c4a82bb0-ba9d-446f-a121-ba7d2996c39e,Jane,Taylor,jane.taylor@example.com,1955-05-29,"766 Cedar St, Madison, FL","Sociology, Biology, Agriculture, Art",766 Cedar St,Madison,FL,Jane Taylor,"b33ae65d-523e-48c6-b10e-59346e1c6523,dda33b53-..."
352,0a10e180-a33a-4d04-8519-ae951f56b478,Sarah,Johnson,sarah.johnson@example.com,1999-12-18,"719 Maple St, Madison, CA","Physics, Biology, History, Social Work, Mathem...",719 Maple St,Madison,CA,Sarah Johnson,"b33ae65d-523e-48c6-b10e-59346e1c6523,9dd4dfda-..."
432,57101157-bd0a-4615-8778-df69fe8360c6,Sarah,Miller,sarah.miller@example.com,1950-06-24,"710 Elm St, Riverside, OH",Psychology,710 Elm St,Riverside,OH,Sarah Miller,"4d0b9e50-43d1-4da0-af2b-97d510bab9e2,049d0ea9-..."

In [137]:
# Merge bed ID from inventory data
occupancy_data = occupancy_data.merge(inventory_data[['buildingName', 'roomName', 'bedName', 'bedId']], on=['buildingName', 'roomName', 'bedName'], how='left')

# Merge person data with occupancy data
final_data = persons_data.merge(occupancy_data[['personId', 'bedId']], on='personId', how='left')

In [138]:
final_data

,personId,firstName,lastName,email,dob,address,majors,address1,city,state,name,majorIds,bedId
0,7b1fb398-72d7-421e-808c-631a427bfbc4,David,Taylor,david.taylor@example.com,1992-08-15,"767 Walnut St, Georgetown, OH",Communications,767 Walnut St,Georgetown,OH,David Taylor,"2c6e4248-da4d-4cb3-ac58-3cd04aa203fa,c8e9582b-...",NaN
1,99a4b233-2804-420b-b757-039f0f3cceb7,Jane,Wilson,jane.wilson@example.com,1969-08-20,"168 Birch St, Riverside, FL","Music, Finance",168 Birch St,Riverside,FL,Jane Wilson,"49f57722-52fb-47b6-8e1e-54de177e0d19,e00c66ff-...",NaN
2,cc3b2df2-a593-493e-af82-1f0d11c7439b,John,Brown,john.brown@example.com,1967-12-14,"726 Maple St, Fairview, PA",NaN,726 Maple St,Fairview,PA,John Brown,,a32b34cf-0356-4739-ab43-4a9ed70818f8
3,cb669177-4020-4284-a3dc-9a0c312411d4,Linda,Taylor,linda.taylor@example.com,1983-12-04,"171 Spruce St, Riverside, TX","Social Work, Anthropology",171 Spruce St,Riverside,TX,Linda Taylor,"37b765f0-fc71-4c9c-838b-f3a5ce0706ff,8402b4cd-...",01f250f6-a3a3-492b-ba52-3f53f4483316
4,ba1443a2-dfeb-441b-b41d-078b36416704,Sarah,Doe,sarah.doe@example.com,1986-08-31,"987 Walnut St, Georgetown, OH","Psychology, Criminal Justice, History, Foreign...",987 Walnut St,Georgetown,OH,Sarah Doe,"4d0b9e50-43d1-4da0-af2b-97d510bab9e2,f6cf2da9-...",f8ef5ea9-e2bf-4eda-9d7a-c7cdf30dc649
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2045e65b-0845-4d48-88f3-19c708a836cf,Michael,Davis,michael.davis@example.com,1991-04-24,"462 Walnut St, Madison, IL","Sociology, Economics, Computer Science",462 Walnut St,Madison,IL,Michael Davis,"12c5d420-9bbc-455d-9794-7780bc5fea5b,2c4e188e-...",NaN
96,c4d33385-848f-42f6-843b-220fa0b0f8fc,Michael,Williams,michael.williams@example.com,1994-08-08,"847 Walnut St, Madison, TX","Urban Planning, Architecture",847 Walnut St,Madison,TX,Michael Williams,"e0bad25d-7fb1-4dd7-a0e8-a11b41dcd281,fa7f1f45-...",3a0cd40a-bd21-4359-9b36-c4bf30380f9b
97,c4a82bb0-ba9d-446f-a121-ba7d2996c39e,Jane,Taylor,jane.taylor@example.com,1955-05-29,"766 Cedar St, Madison, FL","Sociology, Biology, Agriculture, Art",766 Cedar St,Madison,FL,Jane Taylor,"b33ae65d-523e-48c6-b10e-59346e1c6523,dda33b53-...",NaN
98,0a10e180-a33a-4d04-8519-ae951f56b478,Sarah,Johnson,sarah.johnson@example.com,1999-12-18,"719 Maple St, Madison, CA","Physics, Biology, History, Social Work, Mathem...",719 Maple St,Madison,CA,Sarah Johnson,"b33ae65d-523e-48c6-b10e-59346e1c6523,9dd4dfda-...",NaN
99,57101157-bd0a-4615-8778-df69fe8360c6,Sarah,Miller,sarah.miller@example.com,1950-06-24,"710 Elm St, Riverside, OH",Psychology,710 Elm St,Riverside,OH,Sarah Miller,"4d0b9e50-43d1-4da0-af2b-97d510bab9e2,049d0ea9-...",NaN

In [139]:
final_data['address2'] = None
final_data['zip'] = None

In [140]:
# Select and rename final columns
final_data = final_data[['personId', 'name', 'email', 'dob', 'address1','address2', 'city', 'state','zip', 'majorIds', 'bedId']]

In [141]:
final_data

,personId,name,email,dob,address1,address2,city,state,zip,majorIds,bedId
0,7b1fb398-72d7-421e-808c-631a427bfbc4,David Taylor,david.taylor@example.com,1992-08-15,767 Walnut St,None,Georgetown,OH,None,"2c6e4248-da4d-4cb3-ac58-3cd04aa203fa,c8e9582b-...",NaN
1,99a4b233-2804-420b-b757-039f0f3cceb7,Jane Wilson,jane.wilson@example.com,1969-08-20,168 Birch St,None,Riverside,FL,None,"49f57722-52fb-47b6-8e1e-54de177e0d19,e00c66ff-...",NaN
2,cc3b2df2-a593-493e-af82-1f0d11c7439b,John Brown,john.brown@example.com,1967-12-14,726 Maple St,None,Fairview,PA,None,,a32b34cf-0356-4739-ab43-4a9ed70818f8
3,cb669177-4020-4284-a3dc-9a0c312411d4,Linda Taylor,linda.taylor@example.com,1983-12-04,171 Spruce St,None,Riverside,TX,None,"37b765f0-fc71-4c9c-838b-f3a5ce0706ff,8402b4cd-...",01f250f6-a3a3-492b-ba52-3f53f4483316
4,ba1443a2-dfeb-441b-b41d-078b36416704,Sarah Doe,sarah.doe@example.com,1986-08-31,987 Walnut St,None,Georgetown,OH,None,"4d0b9e50-43d1-4da0-af2b-97d510bab9e2,f6cf2da9-...",f8ef5ea9-e2bf-4eda-9d7a-c7cdf30dc649
...,...,...,...,...,...,...,...,...,...,...,...
95,2045e65b-0845-4d48-88f3-19c708a836cf,Michael Davis,michael.davis@example.com,1991-04-24,462 Walnut St,None,Madison,IL,None,"12c5d420-9bbc-455d-9794-7780bc5fea5b,2c4e188e-...",NaN
96,c4d33385-848f-42f6-843b-220fa0b0f8fc,Michael Williams,michael.williams@example.com,1994-08-08,847 Walnut St,None,Madison,TX,None,"e0bad25d-7fb1-4dd7-a0e8-a11b41dcd281,fa7f1f45-...",3a0cd40a-bd21-4359-9b36-c4bf30380f9b
97,c4a82bb0-ba9d-446f-a121-ba7d2996c39e,Jane Taylor,jane.taylor@example.com,1955-05-29,766 Cedar St,None,Madison,FL,None,"b33ae65d-523e-48c6-b10e-59346e1c6523,dda33b53-...",NaN
98,0a10e180-a33a-4d04-8519-ae951f56b478,Sarah Johnson,sarah.johnson@example.com,1999-12-18,719 Maple St,None,Madison,CA,None,"b33ae65d-523e-48c6-b10e-59346e1c6523,9dd4dfda-...",NaN
99,57101157-bd0a-4615-8778-df69fe8360c6,Sarah Miller,sarah.miller@example.com,1950-06-24,710 Elm St,None,Riverside,OH,None,"4d0b9e50-43d1-4da0-af2b-97d510bab9e2,049d0ea9-...",NaN

In [142]:
# Export the final DataFrame to a CSV file
final_data.to_csv('final_data.csv', index=False)

In [ ]:
# prompt: generate steps i used in this colab file for report

steps = [
    "Loaded CSV files into DataFrames",
    "Removed duplicate emails from persons_data",
    "Separated address column into address parts",
    "Created full name column in persons_data",
    "Mapped major names to their IDs in persons_data",
    "Merged bed ID from inventory data into occupancy_data",
    "Merged person data with occupancy data",
    "Added address2 and zip columns to final_data",
    "Selected and renamed final columns",
    "Exported the final DataFrame to a CSV file"
]

print("Steps taken in this Colab file:")
for step in steps:
    print(f"- {step}")